from dativ import dativ

# Dlouhý seznam kombinací jmen a příjmení
print(dativ("Jan Novák"))        # Janovi Novákovi
print(dativ("Petr Svoboda"))     # Petrovi Svobodovi
print(dativ("Tomáš Dvořák"))     # Tomášovi Dvořákovi
print(dativ("Marek Černý"))      # Markovi Černému
print(dativ("Jiří Král"))        # Jiřímu Královi
print(dativ("Václav Kučera"))    # Václavovi Kučerovi
print(dativ("František Horák"))  # Františkovi Horákovi
print(dativ("Ondřej Beneš"))     # Ondřejovi Benešovi
print(dativ("Martin Kovář"))     # Martinovi Kovářovi
print(dativ("Lukáš Veselý"))     # Lukášovi Veselému
print(dativ("David Zeman"))      # Davidovi Zemanovi
print(dativ("Jakub Pokorný"))    # Jakubovi Pokornému
print(dativ("Filip Růžička"))    # Filipovi Růžičkovi
print(dativ("Michal Kolář"))     # Michalovi Kolářovi
print(dativ("Josef Urban"))      # Josefovi Urbanovi
print(dativ("Daniel Vaněk"))     # Danielovi Vaňkovi
print(dativ("Radek Blažek"))     # Radkovi Blažkovi
print(dativ("Štěpán Šimek"))     # Štěpánovi Šimkovi
print(dativ("Roman Polák"))      # Romanovi Polákovi
print(dativ("Aleš Štěpánek"))    # Alešovi Štěpánkovi
print(dativ("Karel Kadlec"))     # Karlovi Kadlecovi
print(dativ("Adam Fiala"))       # Adamovi Fialovi
print(dativ("Matěj Sedláček"))   # Matějovi Sedláčkovi
print(dativ("Patrik Holub"))     # Patrikovi Holubovi
print(dativ("Stanislav Matoušek")) # Stanislavovi Matouškovi
print(dativ("Jaroslav Ševčík"))  # Jaroslavovi Ševčíkovi
print(dativ("Vojtěch Řezníček")) # Vojtěchovi Řezníčkovi
print(dativ("Viktor Doubravský")) # Viktorovi Doubravskému
print(dativ("Robert Hájek"))     # Robertovi Hájkovi
print(dativ("Dominik Valenta"))  # Dominikovi Valentovi
print(dativ("Miroslav Hrubý"))   # Miroslavovi Hrubému
print(dativ("Rudolf Pavlík"))    # Rudolfovi Pavlíkovi
print(dativ("Ivan Mach"))        # Ivanovi Machovi
print(dativ("Igor Bartoš"))      # Igorovi Bartošovi
print(dativ("Samuel Vlček"))     # Samuelovi Vlčkovi
print(dativ("Erik Jelínek"))     # Erikovi Jelínkovi
print(dativ("Bohumil Petřík"))   # Bohumilovi Petříkovi
print(dativ("Jindřich Kopecký")) # Jindřichovi Kopeckému
print(dativ("Otakar Soukup"))    # Otakarovi Soukupovi
print(dativ("Oskar Mašek"))      # Oskarovi Maškovi
print(dativ("Miloš Kalina"))     # Milošovi Kalinovi
print(dativ("Leoš Smetana"))     # Leošovi Smetanovi
print(dativ("Vilém Heřman"))     # Vilémovi Heřmanovi
print(dativ("Tadeáš Petrů"))     # Tadeášovi Petrů
print(dativ("Luboš Havránek"))   # Lubošovi Havránkovi
print(dativ("Šimon Němeček"))    # Šimonovi Němečkovi
print(dativ("Norbert Dohnal"))   # Norbertovi Dohnalovi
print(dativ("Gabriel Gregor"))   # Gabrielovi Gregorovi
print(dativ("Ladislav Šulc"))    # Ladislavovi Šulcovi
print(dativ("Jaroslav Jindra"))  # Jaroslavovi Jindrovi
print(dativ("Radim Matějka"))    # Radimovi Matějkovi

# Test ženských jmen a příjmení
print(dativ("Marie Nováková"))     # Marii Novákové
print(dativ("Anna Svobodová"))     # Anně Svobodové
print(dativ("Eva Dvořáková"))      # Evě Dvořákové
print(dativ("Jana Černá"))         # Janě Černé
print(dativ("Lucie Králová"))      # Lucii Králové
print(dativ("Kateřina Kučerová"))  # Kateřině Kučerové
print(dativ("Veronika Horáková"))  # Veronice Horákové
print(dativ("Tereza Benešová"))    # Tereze Benešové
print(dativ("Hana Kovářová"))      # Haně Kovářové
print(dativ("Alena Veselá"))       # Aleně Veselé
print(dativ("Martina Zemanová"))   # Martině Zemanové
print(dativ("Barbora Pokorná"))    # Barboře Pokorné
print(dativ("Lenka Růžičková"))    # Lence Růžičkové
print(dativ("Eliška Kolářová"))    # Elišce Kolářové
print(dativ("Petra Urbanová"))     # Petře Urbanové
print(dativ("Gabriela Vaňková"))   # Gabriele Vaňkové
print(dativ("Michaela Blažková"))  # Michaele Blažkové
print(dativ("Iva Šimková"))        # Ivě Šimkové
print(dativ("Monika Poláková"))    # Monice Polákové
print(dativ("Simona Štěpánková"))  # Simoně Štěpánkové
print(dativ("Helena Kadlecová"))   # Heleně Kadlecové
print(dativ("Pavla Fialová"))      # Pavle Fialové
print(dativ("Adéla Sedláčková"))   # Adéle Sedláčkové
print(dativ("Kristýna Holubová"))  # Kristýně Holubové
print(dativ("Radka Matoušková"))   # Radce Matouškové
print(dativ("Věra Ševčíková"))     # Věře Ševčíkové
print(dativ("Marcela Řezníčková")) # Marcele Řezníčkové
print(dativ("Jitka Doubravská"))   # Jitce Doubravské
print(dativ("Olga Hájková"))       # Olze Hájkové
print(dativ("Renata Valentová"))   # Renatě Valentové
print(dativ("Dana Hrubá"))         # Daně Hrubé
print(dativ("Dagmar Pavlíková"))   # Dagmar Pavlíkové
print(dativ("Zuzana Machová"))     # Zuzaně Machové
print(dativ("Milena Bartošová"))   # Mileně Bartošové
print(dativ("Klára Vlčková"))      # Kláře Vlčkové
print(dativ("Anežka Jelínková"))   # Anežce Jelínkové
print(dativ("Šárka Petříková"))    # Šárce Petříkové
print(dativ("Ivana Kopecká"))      # Ivaně Kopecké
print(dativ("Tereza Soukupová"))   # Tereze Soukupové
print(dativ("Natálie Mašková"))    # Natálii Maškové
print(dativ("Nikola Kalinová"))    # Nikole Kalinové
print(dativ("Markéta Smetanová"))  # Markétě Smetanové
print(dativ("Iveta Heřmanová"))    # Ivetě Heřmanové
print(dativ("Linda Petrů"))        # Lindě Petrů
print(dativ("Andrea Havránková"))  # Andree Havránkové
print(dativ("Soňa Němečková"))     # Soně Němečkové
print(dativ("Lída Dohnalová"))     # Lídě Dohnalové
print(dativ("Silvie Gregorová"))   # Silvii Gregorové
print(dativ("Ilona Šulcová"))      # Iloně Šulcové